#!/bin/bash

CURRENTDIR=$PWD
echo "Getting necessary configuration files..."
cd $CMSSW_BASE/src/
curl -s https://raw.githubusercontent.com/cms-sw/genproductions/85ccec18763776e0613830cde524bc7a4c77bc49/python/ThirteenTeV/QCD_Pt_30to50_TuneCUETP8M1_13TeV_pythia8_cff.py --retry 2 --create-dirs -o  Configuration/GenProduction/python/ThirteenTeV/QCD_Pt_30to50_TuneCUETP8M1_13TeV_pythia8_cff.py
curl -s https://raw.githubusercontent.com/cms-sw/genproductions/85ccec18763776e0613830cde524bc7a4c77bc49/python/ThirteenTeV/QCD_Pt_50to80_TuneCUETP8M1_13TeV_pythia8_cff.py --retry 2 --create-dirs -o  Configuration/GenProduction/python/ThirteenTeV/QCD_Pt_50to80_TuneCUETP8M1_13TeV_pythia8_cff.py
curl -s https://raw.githubusercontent.com/cms-sw/genproductions/85ccec18763776e0613830cde524bc7a4c77bc49/python/ThirteenTeV/QCD_Pt_80to120_TuneCUETP8M1_13TeV_pythia8_cff.py --retry 2 --create-dirs -o  Configuration/GenProduction/python/ThirteenTeV/QCD_Pt_80to120_TuneCUETP8M1_13TeV_pythia8_cff.py
curl -s https://raw.githubusercontent.com/cms-sw/genproductions/4a9b6e8c7271875d55840f631d358a62787183f9/python/ThirteenTeV/QCD_Pt_120to170_TuneCUETP8M1_13TeV_pythia8_cff.py --retry 2 --create-dirs -o  Configuration/GenProduction/python/ThirteenTeV/QCD_Pt_120to170_TuneCUETP8M1_13TeV_pythia8_cff.py 
curl -s https://raw.githubusercontent.com/cms-sw/genproductions/c59980a427196a369832bae642a5ba26c3072e4c/python/ThirteenTeV/QCD_Pt_170to300_TuneCUETP8M1_13TeV_pythia8_cff.py --retry 2 --create-dirs -o  Configuration/GenProduction/python/ThirteenTeV/QCD_Pt_170to300_TuneCUETP8M1_13TeV_pythia8_cff.py
curl -s https://raw.githubusercontent.com/cms-sw/genproductions/85ccec18763776e0613830cde524bc7a4c77bc49/python/ThirteenTeV/QCD_Pt_300to470_TuneCUETP8M1_13TeV_pythia8_cff.py --retry 2 --create-dirs -o  Configuration/GenProduction/python/ThirteenTeV/QCD_Pt_300to470_TuneCUETP8M1_13TeV_pythia8_cff.py 
curl -s https://raw.githubusercontent.com/cms-sw/genproductions/85ccec18763776e0613830cde524bc7a4c77bc49/python/ThirteenTeV/QCD_Pt_470to600_TuneCUETP8M1_13TeV_pythia8_cff.py --retry 2 --create-dirs -o  Configuration/GenProduction/python/ThirteenTeV/QCD_Pt_470to600_TuneCUETP8M1_13TeV_pythia8_cff.py 
curl -s https://raw.githubusercontent.com/cms-sw/genproductions/85ccec18763776e0613830cde524bc7a4c77bc49/python/ThirteenTeV/QCD_Pt_600to800_TuneCUETP8M1_13TeV_pythia8_cff.py --retry 2 --create-dirs -o  Configuration/GenProduction/python/ThirteenTeV/QCD_Pt_600to800_TuneCUETP8M1_13TeV_pythia8_cff.py 

echo "Recompiling CMSSW to update references..."
scramv1 b

echo "Creating configuration files..."
cd $CURRENTDIR

# QCD_Pt-30to50
#
# FROM McM - BTV-RunIIWinter15GS-00023
# cmsDriver.py Configuration/GenProduction/python/ThirteenTeV/QCD_Pt_30to50_TuneCUETP8M1_13TeV_pythia8_cff.py --fileout file:BTV-RunIIWinter15GS-00023.root --mc --eventcontent RAWSIM --customise SLHCUpgradeSimulations/Configuration/postLS1Customs.customisePostLS1,Configuration/DataProcessing/Utils.addMonitoring --datatier GEN-SIM --conditions MCRUN2_71_V1::All --beamspot NominalCollision2015 --step GEN,SIM --magField 38T_PostLS1 --python_filename BTV-RunIIWinter15GS-00023_1_cfg.py --no_exec -n 78
#
# FROM McM - BTV-RunIISpring15DR74-00048
# cmsDriver.py step1 --filein "dbs:/QCD_Pt_30to50_TuneCUETP8M1_13TeV_pythia8/RunIIWinter15GS-MCRUN2_71_V1-v1/GEN-SIM" --fileout file:BTV-RunIISpring15DR74-00048_step1.root --pileup_input "dbs:/MinBias_TuneCUETP8M1_13TeV-pythia8/RunIIWinter15GS-MCRUN2_71_V1-v1/GEN-SIM" --mc --eventcontent RAWSIM --pileup 2015_25ns_Startup_PoissonOOTPU --customise SLHCUpgradeSimulations/Configuration/postLS1Customs.customisePostLS1,Configuration/DataProcessing/Utils.addMonitoring --datatier GEN-SIM-RAW --conditions MCRUN2_74_V9 --step DIGI,L1,DIGI2RAW,HLT:@frozen25ns --magField 38T_PostLS1 --python_filename BTV-RunIISpring15DR74-00048_1_cfg.py --no_exec -n 82
# cmsDriver.py step2 --filein file:BTV-RunIISpring15DR74-00048_step1.root --fileout file:BTV-RunIISpring15DR74-00048_step2.root --mc --eventcontent AODSIM,DQM --customise SLHCUpgradeSimulations/Configuration/postLS1Customs.customisePostLS1,Configuration/DataProcessing/Utils.addMonitoring --datatier AODSIM,DQMIO --conditions MCRUN2_74_V9 --step RAW2DIGI,L1Reco,RECO,EI,DQM:DQMOfflinePOGMC --magField 38T_PostLS1 --python_filename BTV-RunIISpring15DR74-00048_2_cfg.py --no_exec -n 82 || exit $? ; 
# 
# Our cfg
cmsDriver.py step1 Configuration/GenProduction/python/ThirteenTeV/QCD_Pt_30to50_TuneCUETP8M1_13TeV_pythia8_cff.py --fileout file:QCD_Pt-30to50_step1.root --pileup_input "dbs:/MinBias_TuneCUETP8M1_13TeV-pythia8/RunIIWinter15GS-MCRUN2_71_V1-v1/GEN-SIM" --pileup 2015_25ns_Startup_PoissonOOTPU --mc --eventcontent RAWSIM --customise SLHCUpgradeSimulations/Configuration/postLS1Customs.customisePostLS1,Configuration/DataProcessing/Utils.addMonitoring --datatier GEN-SIM-RAW --conditions MCRUN2_74_V9 --beamspot NominalCollision2015 --step DIGI,L1,DIGI2RAW,HLT:@frozen25ns --magField 38T_PostLS1 --python_filename QCD_Pt-30to50_step1_cfg.py --no_exec -n 1
cmsDriver.py step2 --filein file:QCD_Pt-30to50_step1.root --fileout file:QCD_Pt-30to50_step2.root --mc --eventcontent AODSIM,DQM --customise SLHCUpgradeSimulations/Configuration/postLS1Customs.customisePostLS1,Configuration/DataProcessing/Utils.addMonitoring --datatier AODSIM,DQMIO --conditions MCRUN2_74_V9 --step RAW2DIGI,L1Reco,RECO --magField 38T_PostLS1 --python_filename QCD_Pt-30to50_step2_cfg.py --no_exec -n 1

# QCD_Pt-50to80
#
# FROM McM - BTV-RunIIWinter15GS-00024
# cmsDriver.py Configuration/GenProduction/python/ThirteenTeV/QCD_Pt_50to80_TuneCUETP8M1_13TeV_pythia8_cff.py --fileout file:BTV-RunIIWinter15GS-00024.root --mc --eventcontent RAWSIM --customise SLHCUpgradeSimulations/Configuration/postLS1Customs.customisePostLS1,Configuration/DataProcessing/Utils.addMonitoring --datatier GEN-SIM --conditions MCRUN2_71_V1::All --beamspot NominalCollision2015 --step GEN,SIM --magField 38T_PostLS1 --python_filename BTV-RunIIWinter15GS-00024_1_cfg.py --no_exec -n 64
#
# FROM McM - BTV-RunIISpring15DR74-00049
# cmsDriver.py step1 --filein "dbs:/QCD_Pt_50to80_TuneCUETP8M1_13TeV_pythia8/RunIIWinter15GS-MCRUN2_71_V1-v1/GEN-SIM" --fileout file:BTV-RunIISpring15DR74-00049_step1.root --pileup_input "dbs:/MinBias_TuneCUETP8M1_13TeV-pythia8/RunIIWinter15GS-MCRUN2_71_V1-v1/GEN-SIM" --mc --eventcontent RAWSIM --pileup 2015_25ns_Startup_PoissonOOTPU --customise SLHCUpgradeSimulations/Configuration/postLS1Customs.customisePostLS1,Configuration/DataProcessing/Utils.addMonitoring --datatier GEN-SIM-RAW --conditions MCRUN2_74_V9 --step DIGI,L1,DIGI2RAW,HLT:@frozen25ns --magField 38T_PostLS1 --python_filename BTV-RunIISpring15DR74-00049_1_cfg.py --no_exec -n 82 || exit $? ; 
# cmsDriver.py step2 --filein file:BTV-RunIISpring15DR74-00049_step1.root --fileout file:BTV-RunIISpring15DR74-00049_step2.root --mc --eventcontent AODSIM,DQM --customise SLHCUpgradeSimulations/Configuration/postLS1Customs.customisePostLS1,Configuration/DataProcessing/Utils.addMonitoring --datatier AODSIM,DQMIO --conditions MCRUN2_74_V9 --step RAW2DIGI,L1Reco,RECO,EI,DQM:DQMOfflinePOGMC --magField 38T_PostLS1 --python_filename BTV-RunIISpring15DR74-00049_2_cfg.py --no_exec -n 82 || exit $? ; 
# 
# Our cfg
cmsDriver.py step1 Configuration/GenProduction/python/ThirteenTeV/QCD_Pt_50to80_TuneCUETP8M1_13TeV_pythia8_cff.py --fileout file:QCD_Pt-50to80_step1.root --pileup_input "dbs:/MinBias_TuneCUETP8M1_13TeV-pythia8/RunIIWinter15GS-MCRUN2_71_V1-v1/GEN-SIM" --pileup 2015_25ns_Startup_PoissonOOTPU --mc --eventcontent RAWSIM --customise SLHCUpgradeSimulations/Configuration/postLS1Customs.customisePostLS1,Configuration/DataProcessing/Utils.addMonitoring --datatier GEN-SIM-RAW --conditions MCRUN2_74_V9 --beamspot NominalCollision2015 --step DIGI,L1,DIGI2RAW,HLT:@frozen25ns --magField 38T_PostLS1 --python_filename QCD_Pt-50to80_step1_cfg.py --no_exec -n 1
cmsDriver.py step2 --filein file:QCD_Pt-50to80_step1.root --fileout file:QCD_Pt-50to80_step2.root --mc --eventcontent AODSIM,DQM --customise SLHCUpgradeSimulations/Configuration/postLS1Customs.customisePostLS1,Configuration/DataProcessing/Utils.addMonitoring --datatier AODSIM,DQMIO --conditions MCRUN2_74_V9 --step RAW2DIGI,L1Reco,RECO --magField 38T_PostLS1 --python_filename QCD_Pt-50to80_step2_cfg.py --no_exec -n 1

# QCD_Pt-80to120
#
# FROM McM - BTV-RunIIWinter15GS-00025
# cmsDriver.py Configuration/GenProduction/python/ThirteenTeV/QCD_Pt_80to120_TuneCUETP8M1_13TeV_pythia8_cff.py --fileout file:BTV-RunIIWinter15GS-00025.root --mc --eventcontent RAWSIM --customise SLHCUpgradeSimulations/Configuration/postLS1Customs.customisePostLS1,Configuration/DataProcessing/Utils.addMonitoring --datatier GEN-SIM --conditions MCRUN2_71_V1::All --beamspot NominalCollision2015 --step GEN,SIM --magField 38T_PostLS1 --python_filename BTV-RunIIWinter15GS-00025_1_cfg.py --no_exec -n 26
#
# FROM McM - BTV-RunIISpring15DR74-00050
# cmsDriver.py step1 --filein "dbs:/QCD_Pt_80to120_TuneCUETP8M1_13TeV_pythia8/RunIIWinter15GS-MCRUN2_71_V1-v1/GEN-SIM" --fileout file:BTV-RunIISpring15DR74-00050_step1.root --pileup_input "dbs:/MinBias_TuneCUETP8M1_13TeV-pythia8/RunIIWinter15GS-MCRUN2_71_V1-v1/GEN-SIM" --mc --eventcontent RAWSIM --pileup 2015_25ns_Startup_PoissonOOTPU --customise SLHCUpgradeSimulations/Configuration/postLS1Customs.customisePostLS1,Configuration/DataProcessing/Utils.addMonitoring --datatier GEN-SIM-RAW --conditions MCRUN2_74_V9 --step DIGI,L1,DIGI2RAW,HLT:@frozen25ns --magField 38T_PostLS1 --python_filename BTV-RunIISpring15DR74-00050_1_cfg.py --no_exec -n 82 || exit $? ; 
# cmsDriver.py step2 --filein file:BTV-RunIISpring15DR74-00050_step1.root --fileout file:BTV-RunIISpring15DR74-00050_step2.root --mc --eventcontent AODSIM,DQM --customise SLHCUpgradeSimulations/Configuration/postLS1Customs.customisePostLS1,Configuration/DataProcessing/Utils.addMonitoring --datatier AODSIM,DQMIO --conditions MCRUN2_74_V9 --step RAW2DIGI,L1Reco,RECO,EI,DQM:DQMOfflinePOGMC --magField 38T_PostLS1 --python_filename BTV-RunIISpring15DR74-00050_2_cfg.py --no_exec -n 82 || exit $? ;
# 
# Our cfg
cmsDriver.py step1 Configuration/GenProduction/python/ThirteenTeV/QCD_Pt_80to120_TuneCUETP8M1_13TeV_pythia8_cff.py --fileout file:QCD_Pt-80to120_step1.root --pileup_input "dbs:/MinBias_TuneCUETP8M1_13TeV-pythia8/RunIIWinter15GS-MCRUN2_71_V1-v1/GEN-SIM" --pileup 2015_25ns_Startup_PoissonOOTPU --mc --eventcontent RAWSIM --customise SLHCUpgradeSimulations/Configuration/postLS1Customs.customisePostLS1,Configuration/DataProcessing/Utils.addMonitoring --datatier GEN-SIM-RAW --conditions MCRUN2_74_V9 --beamspot NominalCollision2015 --step DIGI,L1,DIGI2RAW,HLT:@frozen25ns --magField 38T_PostLS1 --python_filename QCD_Pt-80to120_step1_cfg.py --no_exec -n 1
cmsDriver.py step2 --filein file:QCD_Pt-80to120_step1.root --fileout file:QCD_Pt-80to120_step2.root --mc --eventcontent AODSIM,DQM --customise SLHCUpgradeSimulations/Configuration/postLS1Customs.customisePostLS1,Configuration/DataProcessing/Utils.addMonitoring --datatier AODSIM,DQMIO --conditions MCRUN2_74_V9 --step RAW2DIGI,L1Reco,RECO --magField 38T_PostLS1 --python_filename QCD_Pt-80to120_step2_cfg.py --no_exec -n 1

# QCD_Pt-120to170
#
# FROM McM - BTV-RunIIWinter15GS-00026
# cmsDriver.py Configuration/GenProduction/python/ThirteenTeV/QCD_Pt_120to170_TuneCUETP8M1_13TeV_pythia8_cff.py --fileout file:BTV-RunIIWinter15GS-00026.root --mc --eventcontent RAWSIM --customise SLHCUpgradeSimulations/Configuration/postLS1Customs.customisePostLS1,Configuration/DataProcessing/Utils.addMonitoring --datatier GEN-SIM --conditions MCRUN2_71_V1::All --beamspot NominalCollision2015 --step GEN,SIM --magField 38T_PostLS1 --python_filename BTV-RunIIWinter15GS-00026_1_cfg.py --no_exec -n 49
#
# FROM McM - BTV-RunIISpring15DR74-00051
# cmsDriver.py step1 --filein "dbs:/QCD_Pt_120to170_TuneCUETP8M1_13TeV_pythia8/RunIIWinter15GS-MCRUN2_71_V1-v1/GEN-SIM" --fileout file:BTV-RunIISpring15DR74-00051_step1.root --pileup_input "dbs:/MinBias_TuneCUETP8M1_13TeV-pythia8/RunIIWinter15GS-MCRUN2_71_V1-v1/GEN-SIM" --mc --eventcontent RAWSIM --pileup 2015_25ns_Startup_PoissonOOTPU --customise SLHCUpgradeSimulations/Configuration/postLS1Customs.customisePostLS1,Configuration/DataProcessing/Utils.addMonitoring --datatier GEN-SIM-RAW --conditions MCRUN2_74_V9 --step DIGI,L1,DIGI2RAW,HLT:@frozen25ns --magField 38T_PostLS1 --python_filename BTV-RunIISpring15DR74-00051_1_cfg.py --no_exec -n 82 || exit $? ; 
# cmsDriver.py step2 --filein file:BTV-RunIISpring15DR74-00051_step1.root --fileout file:BTV-RunIISpring15DR74-00051_step2.root --mc --eventcontent AODSIM,DQM --customise SLHCUpgradeSimulations/Configuration/postLS1Customs.customisePostLS1,Configuration/DataProcessing/Utils.addMonitoring --datatier AODSIM,DQMIO --conditions MCRUN2_74_V9 --step RAW2DIGI,L1Reco,RECO,EI,DQM:DQMOfflinePOGMC --magField 38T_PostLS1 --python_filename BTV-RunIISpring15DR74-00051_2_cfg.py --no_exec -n 82 || exit $? ; 
# 
# Our cfg
cmsDriver.py step1 Configuration/GenProduction/python/ThirteenTeV/QCD_Pt_120to170_TuneCUETP8M1_13TeV_pythia8_cff.py --fileout file:QCD_Pt-120to170_step1.root --pileup_input "dbs:/MinBias_TuneCUETP8M1_13TeV-pythia8/RunIIWinter15GS-MCRUN2_71_V1-v1/GEN-SIM" --pileup 2015_25ns_Startup_PoissonOOTPU --mc --eventcontent RAWSIM --customise SLHCUpgradeSimulations/Configuration/postLS1Customs.customisePostLS1,Configuration/DataProcessing/Utils.addMonitoring --datatier GEN-SIM-RAW --conditions MCRUN2_74_V9 --beamspot NominalCollision2015 --step DIGI,L1,DIGI2RAW,HLT:@frozen25ns --magField 38T_PostLS1 --python_filename QCD_Pt-120to170_step1_cfg.py --no_exec -n 1
cmsDriver.py step2 --filein file:QCD_Pt-120to170_step1.root --fileout file:QCD_Pt-120to170_step2.root --mc --eventcontent AODSIM,DQM --customise SLHCUpgradeSimulations/Configuration/postLS1Customs.customisePostLS1,Configuration/DataProcessing/Utils.addMonitoring --datatier AODSIM,DQMIO --conditions MCRUN2_74_V9 --step RAW2DIGI,L1Reco,RECO --magField 38T_PostLS1 --python_filename QCD_Pt-120to170_step2_cfg.py --no_exec -n 1

# QCD_Pt-170to300
#
# FROM McM - BTV-RunIIWinter15GS-00027
# cmsDriver.py Configuration/GenProduction/python/ThirteenTeV/QCD_Pt_170to300_TuneCUETP8M1_13TeV_pythia8_cff.py --fileout file:BTV-RunIIWinter15GS-00027.root --mc --eventcontent RAWSIM --customise SLHCUpgradeSimulations/Configuration/postLS1Customs.customisePostLS1,Configuration/DataProcessing/Utils.addMonitoring --datatier GEN-SIM --conditions MCRUN2_71_V1::All --beamspot NominalCollision2015 --step GEN,SIM --magField 38T_PostLS1 --python_filename BTV-RunIIWinter15GS-00027_1_cfg.py --no_exec -n 34
#
# FROM McM - BTV-RunIISpring15DR74-00052
# cmsDriver.py step1 --filein "dbs:/QCD_Pt_170to300_TuneCUETP8M1_13TeV_pythia8/RunIIWinter15GS-MCRUN2_71_V1-v1/GEN-SIM" --fileout file:BTV-RunIISpring15DR74-00052_step1.root --pileup_input "dbs:/MinBias_TuneCUETP8M1_13TeV-pythia8/RunIIWinter15GS-MCRUN2_71_V1-v1/GEN-SIM" --mc --eventcontent RAWSIM --pileup 2015_25ns_Startup_PoissonOOTPU --customise SLHCUpgradeSimulations/Configuration/postLS1Customs.customisePostLS1,Configuration/DataProcessing/Utils.addMonitoring --datatier GEN-SIM-RAW --conditions MCRUN2_74_V9 --step DIGI,L1,DIGI2RAW,HLT:@frozen25ns --magField 38T_PostLS1 --python_filename BTV-RunIISpring15DR74-00052_1_cfg.py --no_exec -n 82 || exit $? ;
# cmsDriver.py step2 --filein file:BTV-RunIISpring15DR74-00052_step1.root --fileout file:BTV-RunIISpring15DR74-00052_step2.root --mc --eventcontent AODSIM,DQM --customise SLHCUpgradeSimulations/Configuration/postLS1Customs.customisePostLS1,Configuration/DataProcessing/Utils.addMonitoring --datatier AODSIM,DQMIO --conditions MCRUN2_74_V9 --step RAW2DIGI,L1Reco,RECO,EI,DQM:DQMOfflinePOGMC --magField 38T_PostLS1 --python_filename BTV-RunIISpring15DR74-00052_2_cfg.py --no_exec -n 82
# 
# Our cfg
cmsDriver.py step1 Configuration/GenProduction/python/ThirteenTeV/QCD_Pt_30to50_TuneCUETP8M1_13TeV_pythia8_cff.py --fileout file:QCD_Pt-30to50_step1.root --pileup_input "dbs:/MinBias_TuneCUETP8M1_13TeV-pythia8/RunIIWinter15GS-MCRUN2_71_V1-v1/GEN-SIM" --pileup 2015_25ns_Startup_PoissonOOTPU --mc --eventcontent RAWSIM --customise SLHCUpgradeSimulations/Configuration/postLS1Customs.customisePostLS1,Configuration/DataProcessing/Utils.addMonitoring --datatier GEN-SIM-RAW --conditions MCRUN2_74_V9 --beamspot NominalCollision2015 --step DIGI,L1,DIGI2RAW,HLT:@frozen25ns --magField 38T_PostLS1 --python_filename QCD_Pt-30to50_step1_cfg.py --no_exec -n 1
cmsDriver.py step2 --filein file:QCD_Pt-30to50_step1.root --fileout file:QCD_Pt-30to50_step2.root --mc --eventcontent AODSIM,DQM --customise SLHCUpgradeSimulations/Configuration/postLS1Customs.customisePostLS1,Configuration/DataProcessing/Utils.addMonitoring --datatier AODSIM,DQMIO --conditions MCRUN2_74_V9 --step RAW2DIGI,L1Reco,RECO --magField 38T_PostLS1 --python_filename QCD_Pt-30to50_step2_cfg.py --no_exec -n 1

# QCD_Pt-300to470
#
# FROM McM - BTV-RunIIWinter15GS-00028
# cmsDriver.py Configuration/GenProduction/python/ThirteenTeV/QCD_Pt_300to470_TuneCUETP8M1_13TeV_pythia8_cff.py --fileout file:BTV-RunIIWinter15GS-00028.root --mc --eventcontent RAWSIM --customise SLHCUpgradeSimulations/Configuration/postLS1Customs.customisePostLS1,Configuration/DataProcessing/Utils.addMonitoring --datatier GEN-SIM --conditions MCRUN2_71_V1::All --beamspot NominalCollision2015 --step GEN,SIM --magField 38T_PostLS1 --python_filename BTV-RunIIWinter15GS-00028_1_cfg.py --no_exec -n 33
#
# FROM McM - BTV-RunIISpring15DR74-00053
# cmsDriver.py step1 --filein "dbs:/QCD_Pt_300to470_TuneCUETP8M1_13TeV_pythia8/RunIIWinter15GS-MCRUN2_71_V1-v1/GEN-SIM" --fileout file:BTV-RunIISpring15DR74-00053_step1.root --pileup_input "dbs:/MinBias_TuneCUETP8M1_13TeV-pythia8/RunIIWinter15GS-MCRUN2_71_V1-v1/GEN-SIM" --mc --eventcontent RAWSIM --pileup 2015_25ns_Startup_PoissonOOTPU --customise SLHCUpgradeSimulations/Configuration/postLS1Customs.customisePostLS1,Configuration/DataProcessing/Utils.addMonitoring --datatier GEN-SIM-RAW --conditions MCRUN2_74_V9 --step DIGI,L1,DIGI2RAW,HLT:@frozen25ns --magField 38T_PostLS1 --python_filename BTV-RunIISpring15DR74-00053_1_cfg.py --no_exec -n 82 || exit $? ; 
# cmsDriver.py step2 --filein file:BTV-RunIISpring15DR74-00053_step1.root --fileout file:BTV-RunIISpring15DR74-00053_step2.root --mc --eventcontent AODSIM,DQM --customise SLHCUpgradeSimulations/Configuration/postLS1Customs.customisePostLS1,Configuration/DataProcessing/Utils.addMonitoring --datatier AODSIM,DQMIO --conditions MCRUN2_74_V9 --step RAW2DIGI,L1Reco,RECO,EI,DQM:DQMOfflinePOGMC --magField 38T_PostLS1 --python_filename BTV-RunIISpring15DR74-00053_2_cfg.py --no_exec -n 82 || exit $? ; 
# 
# Our cfg
cmsDriver.py step1 Configuration/GenProduction/python/ThirteenTeV/QCD_Pt_300to470_TuneCUETP8M1_13TeV_pythia8_cff.py --fileout file:QCD_Pt-300to470_step1.root --pileup_input "dbs:/MinBias_TuneCUETP8M1_13TeV-pythia8/RunIIWinter15GS-MCRUN2_71_V1-v1/GEN-SIM" --pileup 2015_25ns_Startup_PoissonOOTPU --mc --eventcontent RAWSIM --customise SLHCUpgradeSimulations/Configuration/postLS1Customs.customisePostLS1,Configuration/DataProcessing/Utils.addMonitoring --datatier GEN-SIM-RAW --conditions MCRUN2_74_V9 --beamspot NominalCollision2015 --step DIGI,L1,DIGI2RAW,HLT:@frozen25ns --magField 38T_PostLS1 --python_filename QCD_Pt-300to470_step1_cfg.py --no_exec -n 1
cmsDriver.py step2 --filein file:QCD_Pt-300to470_step1.root --fileout file:QCD_Pt-300to470_step2.root --mc --eventcontent AODSIM,DQM --customise SLHCUpgradeSimulations/Configuration/postLS1Customs.customisePostLS1,Configuration/DataProcessing/Utils.addMonitoring --datatier AODSIM,DQMIO --conditions MCRUN2_74_V9 --step RAW2DIGI,L1Reco,RECO --magField 38T_PostLS1 --python_filename QCD_Pt-300to470_step2_cfg.py --no_exec -n 1

# QCD_Pt-470to600
#
# FROM McM - BTV-RunIIWinter15GS-00029
# cmsDriver.py Configuration/GenProduction/python/ThirteenTeV/QCD_Pt_470to600_TuneCUETP8M1_13TeV_pythia8_cff.py --fileout file:BTV-RunIIWinter15GS-00029.root --mc --eventcontent RAWSIM --customise SLHCUpgradeSimulations/Configuration/postLS1Customs.customisePostLS1,Configuration/DataProcessing/Utils.addMonitoring --datatier GEN-SIM --conditions MCRUN2_71_V1::All --beamspot NominalCollision2015 --step GEN,SIM --magField 38T_PostLS1 --python_filename BTV-RunIIWinter15GS-00029_1_cfg.py --no_exec -n 14
#
# FROM McM - BTV-RunIISpring15DR74-00054
# cmsDriver.py step1 --filein "dbs:/QCD_Pt_470to600_TuneCUETP8M1_13TeV_pythia8/RunIIWinter15GS-MCRUN2_71_V1-v1/GEN-SIM" --fileout file:BTV-RunIISpring15DR74-00054_step1.root --pileup_input "dbs:/MinBias_TuneCUETP8M1_13TeV-pythia8/RunIIWinter15GS-MCRUN2_71_V1-v1/GEN-SIM" --mc --eventcontent RAWSIM --pileup 2015_25ns_Startup_PoissonOOTPU --customise SLHCUpgradeSimulations/Configuration/postLS1Customs.customisePostLS1,Configuration/DataProcessing/Utils.addMonitoring --datatier GEN-SIM-RAW --conditions MCRUN2_74_V9 --step DIGI,L1,DIGI2RAW,HLT:@frozen25ns --magField 38T_PostLS1 --python_filename BTV-RunIISpring15DR74-00054_1_cfg.py --no_exec -n 82 || exit $? ; 
# cmsDriver.py step2 --filein file:BTV-RunIISpring15DR74-00054_step1.root --fileout file:BTV-RunIISpring15DR74-00054_step2.root --mc --eventcontent AODSIM,DQM --customise SLHCUpgradeSimulations/Configuration/postLS1Customs.customisePostLS1,Configuration/DataProcessing/Utils.addMonitoring --datatier AODSIM,DQMIO --conditions MCRUN2_74_V9 --step RAW2DIGI,L1Reco,RECO,EI,DQM:DQMOfflinePOGMC --magField 38T_PostLS1 --python_filename BTV-RunIISpring15DR74-00054_2_cfg.py --no_exec -n 82 || exit $? ; 
# 
# Our cfg
cmsDriver.py step1 Configuration/GenProduction/python/ThirteenTeV/QCD_Pt_30to50_TuneCUETP8M1_13TeV_pythia8_cff.py --fileout file:QCD_Pt-30to50_step1.root --pileup_input "dbs:/MinBias_TuneCUETP8M1_13TeV-pythia8/RunIIWinter15GS-MCRUN2_71_V1-v1/GEN-SIM" --pileup 2015_25ns_Startup_PoissonOOTPU --mc --eventcontent RAWSIM --customise SLHCUpgradeSimulations/Configuration/postLS1Customs.customisePostLS1,Configuration/DataProcessing/Utils.addMonitoring --datatier GEN-SIM-RAW --conditions MCRUN2_74_V9 --beamspot NominalCollision2015 --step DIGI,L1,DIGI2RAW,HLT:@frozen25ns --magField 38T_PostLS1 --python_filename QCD_Pt-30to50_step1_cfg.py --no_exec -n 1
cmsDriver.py step2 --filein file:QCD_Pt-30to50_step1.root --fileout file:QCD_Pt-30to50_step2.root --mc --eventcontent AODSIM,DQM --customise SLHCUpgradeSimulations/Configuration/postLS1Customs.customisePostLS1,Configuration/DataProcessing/Utils.addMonitoring --datatier AODSIM,DQMIO --conditions MCRUN2_74_V9 --step RAW2DIGI,L1Reco,RECO --magField 38T_PostLS1 --python_filename QCD_Pt-30to50_step2_cfg.py --no_exec -n 1

# QCD_Pt-600to800
#
# FROM McM - BTV-RunIIWinter15GS-00030
# cmsDriver.py Configuration/GenProduction/python/ThirteenTeV/QCD_Pt_600to800_TuneCUETP8M1_13TeV_pythia8_cff.py --fileout file:BTV-RunIIWinter15GS-00030.root --mc --eventcontent RAWSIM --customise SLHCUpgradeSimulations/Configuration/postLS1Customs.customisePostLS1,Configuration/DataProcessing/Utils.addMonitoring --datatier GEN-SIM --conditions MCRUN2_71_V1::All --beamspot NominalCollision2015 --step GEN,SIM --magField 38T_PostLS1 --python_filename BTV-RunIIWinter15GS-00030_1_cfg.py --no_exec -n 15
#
# FROM McM - BTV-RunIISpring15DR74-00055
# cmsDriver.py step1 --filein "dbs:/QCD_Pt_600to800_TuneCUETP8M1_13TeV_pythia8/RunIIWinter15GS-MCRUN2_71_V1-v1/GEN-SIM" --fileout file:BTV-RunIISpring15DR74-00055_step1.root --pileup_input "dbs:/MinBias_TuneCUETP8M1_13TeV-pythia8/RunIIWinter15GS-MCRUN2_71_V1-v1/GEN-SIM" --mc --eventcontent RAWSIM --pileup 2015_25ns_Startup_PoissonOOTPU --customise SLHCUpgradeSimulations/Configuration/postLS1Customs.customisePostLS1,Configuration/DataProcessing/Utils.addMonitoring --datatier GEN-SIM-RAW --conditions MCRUN2_74_V9 --step DIGI,L1,DIGI2RAW,HLT:@frozen25ns --magField 38T_PostLS1 --python_filename BTV-RunIISpring15DR74-00055_1_cfg.py --no_exec -n 82 || exit $? ; 
# cmsDriver.py step2 --filein file:BTV-RunIISpring15DR74-00055_step1.root --fileout file:BTV-RunIISpring15DR74-00055_step2.root --mc --eventcontent AODSIM,DQM --customise SLHCUpgradeSimulations/Configuration/postLS1Customs.customisePostLS1,Configuration/DataProcessing/Utils.addMonitoring --datatier AODSIM,DQMIO --conditions MCRUN2_74_V9 --step RAW2DIGI,L1Reco,RECO,EI,DQM:DQMOfflinePOGMC --magField 38T_PostLS1 --python_filename BTV-RunIISpring15DR74-00055_2_cfg.py --no_exec -n 82 || exit $? ; 
# 
# Our cfg
cmsDriver.py step1 Configuration/GenProduction/python/ThirteenTeV/QCD_Pt_600to800_TuneCUETP8M1_13TeV_pythia8_cff.py --fileout file:QCD_Pt-600to800_step1.root --pileup_input "dbs:/MinBias_TuneCUETP8M1_13TeV-pythia8/RunIIWinter15GS-MCRUN2_71_V1-v1/GEN-SIM" --pileup 2015_25ns_Startup_PoissonOOTPU --mc --eventcontent RAWSIM --customise SLHCUpgradeSimulations/Configuration/postLS1Customs.customisePostLS1,Configuration/DataProcessing/Utils.addMonitoring --datatier GEN-SIM-RAW --conditions MCRUN2_74_V9 --beamspot NominalCollision2015 --step DIGI,L1,DIGI2RAW,HLT:@frozen25ns --magField 38T_PostLS1 --python_filename QCD_Pt-600to800_step1_cfg.py --no_exec -n 1
cmsDriver.py step2 --filein file:QCD_Pt-600to800_step1.root --fileout file:QCD_Pt-600to800_step2.root --mc --eventcontent AODSIM,DQM --customise SLHCUpgradeSimulations/Configuration/postLS1Customs.customisePostLS1,Configuration/DataProcessing/Utils.addMonitoring --datatier AODSIM,DQMIO --conditions MCRUN2_74_V9 --step RAW2DIGI,L1Reco,RECO --magField 38T_PostLS1 --python_filename QCD_Pt-600to800_step2_cfg.py --no_exec -n 1
