#!/bin/bash

# Getting files
# curl -s --insecure https://cms-pdmv.cern.ch/mcm/public/restapi/requests/get_fragment/BTV-Fall13-00042 --retry 2 --create-dirs -o BTV-Fall13-00042-fragment.py 
# curl -s --insecure https://cms-pdmv.cern.ch/mcm/public/restapi/requests/get_fragment/BTV-Fall13-00043 --retry 2 --create-dirs -o BTV-Fall13-00043-fragment.py 
# curl -s --insecure https://cms-pdmv.cern.ch/mcm/public/restapi/requests/get_fragment/BTV-Fall13-00044 --retry 2 --create-dirs -o BTV-Fall13-00044-fragment.py
# curl -s --insecure https://cms-pdmv.cern.ch/mcm/public/restapi/requests/get_fragment/BTV-Fall13-00045 --retry 2 --create-dirs -o BTV-Fall13-00045-fragment.py 
# curl -s --insecure https://cms-pdmv.cern.ch/mcm/public/restapi/requests/get_fragment/BTV-Fall13-00046 --retry 2 --create-dirs -o BTV-Fall13-00046-fragment.py
# curl -s --insecure https://cms-pdmv.cern.ch/mcm/public/restapi/requests/get_fragment/BTV-Fall13-00047 --retry 2 --create-dirs -o BTV-Fall13-00047-fragment.py
# curl -s --insecure https://cms-pdmv.cern.ch/mcm/public/restapi/requests/get_fragment/BTV-Fall13-00048 --retry 2 --create-dirs -o BTV-Fall13-00048-fragment.py
# curl -s --insecure https://cms-pdmv.cern.ch/mcm/public/restapi/requests/get_fragment/BTV-Fall13-00049 --retry 2 --create-dirs -o BTV-Fall13-00049-fragment.py

# QCD_Pt-30to50
#cmsDriver.py step1 --filein "dbs:/QCD_Pt-30to50_Tune4C_13TeV_pythia8/Fall13-POSTLS162_V1_castor-v1/GEN-SIM" --fileout file:QCD_Pt-30to50_step1.root --pileup_input "dbs:/MinBias_TuneA2MB_13TeV-pythia8/Fall13-POSTLS162_V1-v1/GEN-SIM" --mc --eventcontent RAWSIM --inputEventContent REGEN --pileup 'AVE_35_BX_50ns,{"N":30}' --customise SLHCUpgradeSimulations/Configuration/postLS1Customs.customisePostLS1,Configuration/DataProcessing/Utils.addMonitoring --datatier GEN-SIM-RAW --conditions PHYS14_ST_V1 --step GEN:fixGenInfo,DIGI,L1,DIGI2RAW,HLT:GRun --magField 38T_PostLS1 --python_filename QCD_Pt-30to50_step1_cfg.py --no_exec -n 100
cmsDriver.py Configuration/GenProduction/python/BTV-Fall13-00042-fragment.py --fileout file:QCD_Pt-30to50_step1.root --mc --eventcontent RAWSIM --customise SLHCUpgradeSimulations/Configuration/postLS1Customs.customisePostLS1,Configuration/StandardSequences/SimWithCastor_cff.customise --datatier GEN-SIM-RAW --pileup_input "dbs:/MinBias_TuneA2MB_13TeV-pythia8/Fall13-POSTLS162_V1-v1/GEN-SIM" --pileup 'AVE_35_BX_50ns,{"N":30}' --conditions PHYS14_ST_V1 --step GEN,SIM,DIGI,L1,DIGI2RAW,HLT:GRun --magField 38T_PostLS1 --geometry Extended2015 --python_filename QCD_Pt-30to50_step1_cfg.py --no_exec -n 100
cmsDriver.py step2 --filein file:QCD_Pt-30to50_step1.root --fileout file:QCD_Pt-30to50_step2.root --mc --eventcontent AODSIM --customise SLHCUpgradeSimulations/Configuration/postLS1Customs.customisePostLS1,Configuration/DataProcessing/Utils.addMonitoring --datatier AODSIM --conditions PHYS14_ST_V1 --step RAW2DIGI,L1Reco,RECO --magField 38T_PostLS1 --python_filename QCD_Pt-30to50_step2_cfg.py --no_exec -n 100

# QCD_Pt-50to80
#cmsDriver.py step1 --filein "dbs:/QCD_Pt-50to80_Tune4C_13TeV_pythia8/Fall13-POSTLS162_V1_castor-v1/GEN-SIM" --fileout file:QCD_Pt-50to80_step1.root --pileup_input "dbs:/MinBias_TuneA2MB_13TeV-pythia8/Fall13-POSTLS162_V1-v1/GEN-SIM" --mc --eventcontent RAWSIM --inputEventContent REGEN --pileup 'AVE_35_BX_50ns,{"N":30}' --customise SLHCUpgradeSimulations/Configuration/postLS1Customs.customisePostLS1,Configuration/DataProcessing/Utils.addMonitoring --datatier GEN-SIM-RAW --conditions PHYS14_ST_V1 --step GEN:fixGenInfo,DIGI,L1,DIGI2RAW,HLT:GRun --magField 38T_PostLS1 --python_filename QCD_Pt-50to80_step1_cfg.py --no_exec -n 100
cmsDriver.py Configuration/GenProduction/python/BTV-Fall13-00043-fragment.py --fileout file:QCD_Pt-50to80_step1.root --mc --eventcontent RAWSIM --customise SLHCUpgradeSimulations/Configuration/postLS1Customs.customisePostLS1,Configuration/StandardSequences/SimWithCastor_cff.customise --datatier GEN-SIM-RAW --pileup_input "dbs:/MinBias_TuneA2MB_13TeV-pythia8/Fall13-POSTLS162_V1-v1/GEN-SIM" --pileup 'AVE_35_BX_50ns,{"N":30}' --conditions PHYS14_ST_V1 --step GEN,SIM,DIGI,L1,DIGI2RAW,HLT:GRun --magField 38T_PostLS1 --geometry Extended2015 --python_filename QCD_Pt-50to80_step1_cfg.py --no_exec -n 100
cmsDriver.py step2 --filein file:QCD_Pt-50to80_step1.root --fileout file:QCD_Pt-50to80_step2.root --mc --eventcontent AODSIM --customise SLHCUpgradeSimulations/Configuration/postLS1Customs.customisePostLS1,Configuration/DataProcessing/Utils.addMonitoring --datatier AODSIM --conditions PHYS14_ST_V1 --step RAW2DIGI,L1Reco,RECO, --magField 38T_PostLS1 --python_filename QCD_Pt-50to80_step2_cfg.py --no_exec -n 100

# QCD_Pt-80to120
#cmsDriver.py step1 --filein "dbs:/QCD_Pt-80to120_Tune4C_13TeV_pythia8/Fall13-POSTLS162_V1_castor-v1/GEN-SIM" --fileout file:QCD_Pt-80to120_step1.root --pileup_input "dbs:/MinBias_TuneA2MB_13TeV-pythia8/Fall13-POSTLS162_V1-v1/GEN-SIM" --mc --eventcontent RAWSIM --inputEventContent REGEN --pileup 'AVE_35_BX_50ns,{"N":30}' --customise SLHCUpgradeSimulations/Configuration/postLS1Customs.customisePostLS1,Configuration/DataProcessing/Utils.addMonitoring --datatier GEN-SIM-RAW --conditions PHYS14_ST_V1 --step GEN:fixGenInfo,DIGI,L1,DIGI2RAW,HLT:GRun --magField 38T_PostLS1 --python_filename QCD_Pt-80to120_step1_cfg.py --no_exec -n 100
cmsDriver.py Configuration/GenProduction/python/BTV-Fall13-00044-fragment.py --fileout file:QCD_Pt-80to120_step1.root --mc --eventcontent RAWSIM --customise SLHCUpgradeSimulations/Configuration/postLS1Customs.customisePostLS1,Configuration/StandardSequences/SimWithCastor_cff.customise --datatier GEN-SIM-RAW --pileup_input "dbs:/MinBias_TuneA2MB_13TeV-pythia8/Fall13-POSTLS162_V1-v1/GEN-SIM" --pileup 'AVE_35_BX_50ns,{"N":30}' --conditions PHYS14_ST_V1 --step GEN,SIM,DIGI,L1,DIGI2RAW,HLT:GRun --magField 38T_PostLS1 --geometry Extended2015 --python_filename QCD_Pt-80to120_step1_cfg.py --no_exec -n 100
cmsDriver.py step2 --filein file:QCD_Pt-80to120_step1.root --fileout file:QCD_Pt-80to120_step2.root --mc --eventcontent AODSIM --customise SLHCUpgradeSimulations/Configuration/postLS1Customs.customisePostLS1,Configuration/DataProcessing/Utils.addMonitoring --datatier AODSIM --conditions PHYS14_ST_V1 --step RAW2DIGI,L1Reco,RECO --magField 38T_PostLS1 --python_filename QCD_Pt-80to120_step2_cfg.py --no_exec -n 100

# QCD_Pt-120to170
#cmsDriver.py step1 --filein "dbs:/QCD_Pt-120to170_Tune4C_13TeV_pythia8/Fall13-POSTLS162_V1_castor-v1/GEN-SIM" --fileout file:QCD_Pt-120to170_step1.root --pileup_input "dbs:/MinBias_TuneA2MB_13TeV-pythia8/Fall13-POSTLS162_V1-v1/GEN-SIM" --mc --eventcontent RAWSIM --inputEventContent REGEN --pileup 'AVE_35_BX_50ns,{"N":30}' --customise SLHCUpgradeSimulations/Configuration/postLS1Customs.customisePostLS1,Configuration/DataProcessing/Utils.addMonitoring --datatier GEN-SIM-RAW --conditions PHYS14_ST_V1 --step GEN:fixGenInfo,DIGI,L1,DIGI2RAW,HLT:GRun --magField 38T_PostLS1 --python_filename QCD_Pt-120to170_step1_cfg.py --no_exec -n 100
cmsDriver.py Configuration/GenProduction/python/BTV-Fall13-00045-fragment.py --fileout file:QCD_Pt-120to170_step1.root --mc --eventcontent RAWSIM --customise SLHCUpgradeSimulations/Configuration/postLS1Customs.customisePostLS1,Configuration/StandardSequences/SimWithCastor_cff.customise --datatier GEN-SIM-RAW --pileup_input "dbs:/MinBias_TuneA2MB_13TeV-pythia8/Fall13-POSTLS162_V1-v1/GEN-SIM" --pileup 'AVE_35_BX_50ns,{"N":30}' --conditions PHYS14_ST_V1 --step GEN,SIM,DIGI,L1,DIGI2RAW,HLT:GRun --magField 38T_PostLS1 --geometry Extended2015 --python_filename QCD_Pt-120to170_step1_cfg.py --no_exec -n 100
cmsDriver.py step2 --filein file:QCD_Pt-120to170_step1.root --fileout file:QCD_Pt-120to170_step2.root --mc --eventcontent AODSIM --customise SLHCUpgradeSimulations/Configuration/postLS1Customs.customisePostLS1,Configuration/DataProcessing/Utils.addMonitoring --datatier AODSIM --conditions PHYS14_ST_V1 --step RAW2DIGI,L1Reco,RECO --magField 38T_PostLS1 --python_filename QCD_Pt-120to170_step2_cfg.py --no_exec -n 100

# QCD_Pt-170to300
#cmsDriver.py step1 --filein "dbs:/QCD_Pt-170to300_Tune4C_13TeV_pythia8/Fall13-POSTLS162_V1_castor-v1/GEN-SIM" --fileout file:QCD_Pt-170to300_step1.root --pileup_input "dbs:/MinBias_TuneA2MB_13TeV-pythia8/Fall13-POSTLS162_V1-v1/GEN-SIM" --mc --eventcontent RAWSIM --inputEventContent REGEN --pileup 'AVE_35_BX_50ns,{"N":30}' --customise SLHCUpgradeSimulations/Configuration/postLS1Customs.customisePostLS1,Configuration/DataProcessing/Utils.addMonitoring --datatier GEN-SIM-RAW --conditions PHYS14_ST_V1 --step GEN:fixGenInfo,DIGI,L1,DIGI2RAW,HLT:GRun --magField 38T_PostLS1 --python_filename QCD_Pt-170to300_step1_cfg.py --no_exec -n 100
cmsDriver.py Configuration/GenProduction/python/BTV-Fall13-00046-fragment.py --fileout file:QCD_Pt-170to300_step1.root --mc --eventcontent RAWSIM --customise SLHCUpgradeSimulations/Configuration/postLS1Customs.customisePostLS1,Configuration/StandardSequences/SimWithCastor_cff.customise --datatier GEN-SIM-RAW --pileup_input "dbs:/MinBias_TuneA2MB_13TeV-pythia8/Fall13-POSTLS162_V1-v1/GEN-SIM" --pileup 'AVE_35_BX_50ns,{"N":30}' --conditions PHYS14_ST_V1 --step GEN,SIM,DIGI,L1,DIGI2RAW,HLT:GRun --magField 38T_PostLS1 --geometry Extended2015 --python_filename QCD_Pt-170to300_step1_cfg.py --no_exec -n 100
cmsDriver.py step2 --filein file:QCD_Pt-170to300_step1.root --fileout file:QCD_Pt-170to300_step2.root --mc --eventcontent AODSIM --customise SLHCUpgradeSimulations/Configuration/postLS1Customs.customisePostLS1,Configuration/DataProcessing/Utils.addMonitoring --datatier AODSIM --conditions PHYS14_ST_V1 --step RAW2DIGI,L1Reco,RECO --magField 38T_PostLS1 --python_filename QCD_Pt-170to300_step2_cfg.py --no_exec -n 100

# QCD_Pt-300to470
#cmsDriver.py step1 --filein "dbs:/QCD_Pt-300to470_Tune4C_13TeV_pythia8/Fall13-POSTLS162_V1_castor-v1/GEN-SIM" --fileout file:QCD_Pt-300to470_step1.root --pileup_input "dbs:/MinBias_TuneA2MB_13TeV-pythia8/Fall13-POSTLS162_V1-v1/GEN-SIM" --mc --eventcontent RAWSIM --inputEventContent REGEN --pileup 'AVE_35_BX_50ns,{"N":30}' --customise SLHCUpgradeSimulations/Configuration/postLS1Customs.customisePostLS1,Configuration/DataProcessing/Utils.addMonitoring --datatier GEN-SIM-RAW --conditions PHYS14_ST_V1 --step GEN:fixGenInfo,DIGI,L1,DIGI2RAW,HLT:GRun --magField 38T_PostLS1 --python_filename QCD_Pt-300to470_step1_cfg.py --no_exec -n 100
cmsDriver.py Configuration/GenProduction/python/BTV-Fall13-00047-fragment.py --fileout file:QCD_Pt-300to470_step1.root --mc --eventcontent RAWSIM --customise SLHCUpgradeSimulations/Configuration/postLS1Customs.customisePostLS1,Configuration/StandardSequences/SimWithCastor_cff.customise --datatier GEN-SIM-RAW --pileup_input "dbs:/MinBias_TuneA2MB_13TeV-pythia8/Fall13-POSTLS162_V1-v1/GEN-SIM" --pileup 'AVE_35_BX_50ns,{"N":30}' --conditions PHYS14_ST_V1 --step GEN,SIM,DIGI,L1,DIGI2RAW,HLT:GRun --magField 38T_PostLS1 --geometry Extended2015 --python_filename QCD_Pt-300to470_step1_cfg.py --no_exec -n 100
cmsDriver.py step2 --filein file:QCD_Pt-300to470_step1.root --fileout file:QCD_Pt-300to470_step2.root --mc --eventcontent AODSIM --customise SLHCUpgradeSimulations/Configuration/postLS1Customs.customisePostLS1,Configuration/DataProcessing/Utils.addMonitoring --datatier AODSIM --conditions PHYS14_ST_V1 --step RAW2DIGI,L1Reco,RECO --magField 38T_PostLS1 --python_filename QCD_Pt-300to470_step2_cfg.py --no_exec -n 100

# QCD_Pt-470to600
#cmsDriver.py step1 --filein "dbs:/QCD_Pt-470to600_Tune4C_13TeV_pythia8/Fall13-POSTLS162_V1_castor-v1/GEN-SIM" --fileout file:QCD_Pt-470to600_step1.root --pileup_input "dbs:/MinBias_TuneA2MB_13TeV-pythia8/Fall13-POSTLS162_V1-v1/GEN-SIM" --mc --eventcontent RAWSIM --inputEventContent REGEN --pileup 'AVE_35_BX_50ns,{"N":30}' --customise SLHCUpgradeSimulations/Configuration/postLS1Customs.customisePostLS1,Configuration/DataProcessing/Utils.addMonitoring --datatier GEN-SIM-RAW --conditions PHYS14_ST_V1 --step GEN:fixGenInfo,DIGI,L1,DIGI2RAW,HLT:GRun --magField 38T_PostLS1 --python_filename QCD_Pt-470to600_step1_cfg.py --no_exec -n 100
cmsDriver.py Configuration/GenProduction/python/BTV-Fall13-00048-fragment.py --fileout file:QCD_Pt-470to600_step1.root --mc --eventcontent RAWSIM --customise SLHCUpgradeSimulations/Configuration/postLS1Customs.customisePostLS1,Configuration/StandardSequences/SimWithCastor_cff.customise --datatier GEN-SIM-RAW --pileup_input "dbs:/MinBias_TuneA2MB_13TeV-pythia8/Fall13-POSTLS162_V1-v1/GEN-SIM" --pileup 'AVE_35_BX_50ns,{"N":30}' --conditions PHYS14_ST_V1 --step GEN,SIM,DIGI,L1,DIGI2RAW,HLT:GRun --magField 38T_PostLS1 --geometry Extended2015 --python_filename QCD_Pt-470to600_step1_cfg.py --no_exec -n 100
cmsDriver.py step2 --filein file:QCD_Pt-470to600_step1.root --fileout file:QCD_Pt-470to600_step2.root --mc --eventcontent AODSIM --customise SLHCUpgradeSimulations/Configuration/postLS1Customs.customisePostLS1,Configuration/DataProcessing/Utils.addMonitoring --datatier AODSIM --conditions PHYS14_ST_V1 --step RAW2DIGI,L1Reco,RECO --magField 38T_PostLS1 --python_filename QCD_Pt-470to600_step2_cfg.py --no_exec -n 100

# QCD_Pt-600to800
#cmsDriver.py step1 --filein "dbs:/QCD_Pt-600to800_Tune4C_13TeV_pythia8/Fall13-POSTLS162_V1_castor-v1/GEN-SIM" --fileout file:QCD_Pt-600to800_step1.root --pileup_input "dbs:/MinBias_TuneA2MB_13TeV-pythia8/Fall13-POSTLS162_V1-v1/GEN-SIM" --mc --eventcontent RAWSIM --inputEventContent REGEN --pileup 'AVE_35_BX_50ns,{"N":30}' --customise SLHCUpgradeSimulations/Configuration/postLS1Customs.customisePostLS1,Configuration/DataProcessing/Utils.addMonitoring --datatier GEN-SIM-RAW --conditions PHYS14_ST_V1 --step GEN:fixGenInfo,DIGI,L1,DIGI2RAW,HLT:GRun --magField 38T_PostLS1 --python_filename QCD_Pt-600to800_step1_cfg.py --no_exec -n 100
cmsDriver.py Configuration/GenProduction/python/BTV-Fall13-00049-fragment.py --fileout file:QCD_Pt-600to800_step1.root --mc --eventcontent RAWSIM --customise SLHCUpgradeSimulations/Configuration/postLS1Customs.customisePostLS1,Configuration/StandardSequences/SimWithCastor_cff.customise --datatier GEN-SIM-RAW --pileup_input "dbs:/MinBias_TuneA2MB_13TeV-pythia8/Fall13-POSTLS162_V1-v1/GEN-SIM" --pileup 'AVE_35_BX_50ns,{"N":30}' --conditions PHYS14_ST_V1 --step GEN,SIM,DIGI,L1,DIGI2RAW,HLT:GRun --magField 38T_PostLS1 --geometry Extended2015 --python_filename QCD_Pt-600to800_step1_cfg.py --no_exec -n 100
cmsDriver.py step2 --filein file:QCD_Pt-600to800_step1.root --fileout file:QCD_Pt-600to800_step2.root --mc --eventcontent AODSIM --customise SLHCUpgradeSimulations/Configuration/postLS1Customs.customisePostLS1,Configuration/DataProcessing/Utils.addMonitoring --datatier AODSIM --conditions PHYS14_ST_V1 --step RAW2DIGI,L1Reco,RECO --magField 38T_PostLS1 --python_filename QCD_Pt-600to800_step2_cfg.py --no_exec -n 100






# Configuration/GenProduction/python/EightTeV/QCD_Pt_30to50_TuneZ2star_8TeV_pythia6_cff.py 
# --step GEN,SIM --beamspot Realistic8TeVCollision 
# --conditions START50_V13::All 
# --pileup NoPileUp 
# --datamix NODATAMIXER 
# --customise Configuration/StandardSequences/SimWithCastor_cff.customise 
# --eventcontent RAWSIM 
# --datatier GEN-SIM
